//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientesPedidos.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientesEx", Namespace="http://schemas.datacontract.org/2004/07/Datos.ClasEx")]
    [System.SerializableAttribute()]
    public partial class ClientesEx : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> EstatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Estatus {
            get {
                return this.EstatusField;
            }
            set {
                if ((this.EstatusField.Equals(value) != true)) {
                    this.EstatusField = value;
                    this.RaisePropertyChanged("Estatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdC {
            get {
                return this.IdCField;
            }
            set {
                if ((this.IdCField.Equals(value) != true)) {
                    this.IdCField = value;
                    this.RaisePropertyChanged("IdC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IServiceClientes")]
    public interface IServiceClientes {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceClientes/Obtener", ReplyAction="http://tempuri.org/IServiceClientes/ObtenerResponse")]
        ClientesPedidos.ServiceReference2.ClientesEx[] Obtener();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceClientes/Obtener", ReplyAction="http://tempuri.org/IServiceClientes/ObtenerResponse")]
        System.Threading.Tasks.Task<ClientesPedidos.ServiceReference2.ClientesEx[]> ObtenerAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceClientesChannel : ClientesPedidos.ServiceReference2.IServiceClientes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClientesClient : System.ServiceModel.ClientBase<ClientesPedidos.ServiceReference2.IServiceClientes>, ClientesPedidos.ServiceReference2.IServiceClientes {
        
        public ServiceClientesClient() {
        }
        
        public ServiceClientesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClientesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClientesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClientesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClientesPedidos.ServiceReference2.ClientesEx[] Obtener() {
            return base.Channel.Obtener();
        }
        
        public System.Threading.Tasks.Task<ClientesPedidos.ServiceReference2.ClientesEx[]> ObtenerAsync() {
            return base.Channel.ObtenerAsync();
        }
    }
}
