//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientesPedidos.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PedidosEx", Namespace="http://schemas.datacontract.org/2004/07/Datos.ClasEx")]
    [System.SerializableAttribute()]
    public partial class PedidosEx : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientesPedidos.ServiceReference1.ClientesEx ClientesExField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ClientesIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientesPedidos.ServiceReference1.ProdEx ProdExField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ProductosIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientesPedidos.ServiceReference1.ClientesEx ClientesEx {
            get {
                return this.ClientesExField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientesExField, value) != true)) {
                    this.ClientesExField = value;
                    this.RaisePropertyChanged("ClientesEx");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ClientesId {
            get {
                return this.ClientesIdField;
            }
            set {
                if ((this.ClientesIdField.Equals(value) != true)) {
                    this.ClientesIdField = value;
                    this.RaisePropertyChanged("ClientesId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaPedido {
            get {
                return this.FechaPedidoField;
            }
            set {
                if ((this.FechaPedidoField.Equals(value) != true)) {
                    this.FechaPedidoField = value;
                    this.RaisePropertyChanged("FechaPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdP {
            get {
                return this.IdPField;
            }
            set {
                if ((this.IdPField.Equals(value) != true)) {
                    this.IdPField = value;
                    this.RaisePropertyChanged("IdP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nota {
            get {
                return this.NotaField;
            }
            set {
                if ((object.ReferenceEquals(this.NotaField, value) != true)) {
                    this.NotaField = value;
                    this.RaisePropertyChanged("Nota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientesPedidos.ServiceReference1.ProdEx ProdEx {
            get {
                return this.ProdExField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdExField, value) != true)) {
                    this.ProdExField = value;
                    this.RaisePropertyChanged("ProdEx");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProductosId {
            get {
                return this.ProductosIdField;
            }
            set {
                if ((this.ProductosIdField.Equals(value) != true)) {
                    this.ProductosIdField = value;
                    this.RaisePropertyChanged("ProductosId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientesEx", Namespace="http://schemas.datacontract.org/2004/07/Datos.ClasEx")]
    [System.SerializableAttribute()]
    public partial class ClientesEx : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> EstatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Estatus {
            get {
                return this.EstatusField;
            }
            set {
                if ((this.EstatusField.Equals(value) != true)) {
                    this.EstatusField = value;
                    this.RaisePropertyChanged("Estatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdC {
            get {
                return this.IdCField;
            }
            set {
                if ((this.IdCField.Equals(value) != true)) {
                    this.IdCField = value;
                    this.RaisePropertyChanged("IdC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProdEx", Namespace="http://schemas.datacontract.org/2004/07/Datos.ClasEx")]
    [System.SerializableAttribute()]
    public partial class ProdEx : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> EstatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idProField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Estatus {
            get {
                return this.EstatusField;
            }
            set {
                if ((this.EstatusField.Equals(value) != true)) {
                    this.EstatusField = value;
                    this.RaisePropertyChanged("Estatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPro {
            get {
                return this.idProField;
            }
            set {
                if ((this.idProField.Equals(value) != true)) {
                    this.idProField = value;
                    this.RaisePropertyChanged("idPro");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServicePedidos")]
    public interface IServicePedidos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/Obtener", ReplyAction="http://tempuri.org/IServicePedidos/ObtenerResponse")]
        ClientesPedidos.ServiceReference1.PedidosEx[] Obtener();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/Obtener", ReplyAction="http://tempuri.org/IServicePedidos/ObtenerResponse")]
        System.Threading.Tasks.Task<ClientesPedidos.ServiceReference1.PedidosEx[]> ObtenerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/Agregar", ReplyAction="http://tempuri.org/IServicePedidos/AgregarResponse")]
        void Agregar(ClientesPedidos.ServiceReference1.PedidosEx pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/Agregar", ReplyAction="http://tempuri.org/IServicePedidos/AgregarResponse")]
        System.Threading.Tasks.Task AgregarAsync(ClientesPedidos.ServiceReference1.PedidosEx pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/Editar", ReplyAction="http://tempuri.org/IServicePedidos/EditarResponse")]
        void Editar(ClientesPedidos.ServiceReference1.PedidosEx pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/Editar", ReplyAction="http://tempuri.org/IServicePedidos/EditarResponse")]
        System.Threading.Tasks.Task EditarAsync(ClientesPedidos.ServiceReference1.PedidosEx pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/Eliminar", ReplyAction="http://tempuri.org/IServicePedidos/EliminarResponse")]
        void Eliminar(ClientesPedidos.ServiceReference1.PedidosEx pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/Eliminar", ReplyAction="http://tempuri.org/IServicePedidos/EliminarResponse")]
        System.Threading.Tasks.Task EliminarAsync(ClientesPedidos.ServiceReference1.PedidosEx pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/BuscarPorClientes", ReplyAction="http://tempuri.org/IServicePedidos/BuscarPorClientesResponse")]
        ClientesPedidos.ServiceReference1.PedidosEx[] BuscarPorClientes(string texto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/BuscarPorClientes", ReplyAction="http://tempuri.org/IServicePedidos/BuscarPorClientesResponse")]
        System.Threading.Tasks.Task<ClientesPedidos.ServiceReference1.PedidosEx[]> BuscarPorClientesAsync(string texto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/BuscarPorId", ReplyAction="http://tempuri.org/IServicePedidos/BuscarPorIdResponse")]
        ClientesPedidos.ServiceReference1.PedidosEx BuscarPorId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePedidos/BuscarPorId", ReplyAction="http://tempuri.org/IServicePedidos/BuscarPorIdResponse")]
        System.Threading.Tasks.Task<ClientesPedidos.ServiceReference1.PedidosEx> BuscarPorIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicePedidosChannel : ClientesPedidos.ServiceReference1.IServicePedidos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicePedidosClient : System.ServiceModel.ClientBase<ClientesPedidos.ServiceReference1.IServicePedidos>, ClientesPedidos.ServiceReference1.IServicePedidos {
        
        public ServicePedidosClient() {
        }
        
        public ServicePedidosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicePedidosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePedidosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePedidosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClientesPedidos.ServiceReference1.PedidosEx[] Obtener() {
            return base.Channel.Obtener();
        }
        
        public System.Threading.Tasks.Task<ClientesPedidos.ServiceReference1.PedidosEx[]> ObtenerAsync() {
            return base.Channel.ObtenerAsync();
        }
        
        public void Agregar(ClientesPedidos.ServiceReference1.PedidosEx pedido) {
            base.Channel.Agregar(pedido);
        }
        
        public System.Threading.Tasks.Task AgregarAsync(ClientesPedidos.ServiceReference1.PedidosEx pedido) {
            return base.Channel.AgregarAsync(pedido);
        }
        
        public void Editar(ClientesPedidos.ServiceReference1.PedidosEx pedido) {
            base.Channel.Editar(pedido);
        }
        
        public System.Threading.Tasks.Task EditarAsync(ClientesPedidos.ServiceReference1.PedidosEx pedido) {
            return base.Channel.EditarAsync(pedido);
        }
        
        public void Eliminar(ClientesPedidos.ServiceReference1.PedidosEx pedido) {
            base.Channel.Eliminar(pedido);
        }
        
        public System.Threading.Tasks.Task EliminarAsync(ClientesPedidos.ServiceReference1.PedidosEx pedido) {
            return base.Channel.EliminarAsync(pedido);
        }
        
        public ClientesPedidos.ServiceReference1.PedidosEx[] BuscarPorClientes(string texto) {
            return base.Channel.BuscarPorClientes(texto);
        }
        
        public System.Threading.Tasks.Task<ClientesPedidos.ServiceReference1.PedidosEx[]> BuscarPorClientesAsync(string texto) {
            return base.Channel.BuscarPorClientesAsync(texto);
        }
        
        public ClientesPedidos.ServiceReference1.PedidosEx BuscarPorId(int id) {
            return base.Channel.BuscarPorId(id);
        }
        
        public System.Threading.Tasks.Task<ClientesPedidos.ServiceReference1.PedidosEx> BuscarPorIdAsync(int id) {
            return base.Channel.BuscarPorIdAsync(id);
        }
    }
}
